######################################################################
##
## Filename: lcd_module_lcd_module_sch_tb.udo
## Created on: Mon Apr 18 09:55:46 Środkowoeuropejski czas letni 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
