######################################################################
##
## Filename: lcd_init.udo
## Created on: Mon Mar 07 09:54:05 Środkowoeuropejski czas stand. 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
