######################################################################
##
## Filename: lcd_module.udo
## Created on: Fri May 13 10:36:11 Środkowoeuropejski czas letni 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
