######################################################################
##
## Filename: send_4bits.udo
## Created on: Mon Apr 04 09:31:27 Środkowoeuropejski czas letni 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
