######################################################################
##
## Filename: send_4bits_tb.udo
## Created on: Mon Apr 04 09:29:19 Środkowoeuropejski czas letni 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
